### ISSUE TITLE
Doesn't work with CRA 3.0.1

### ISSUE THREAD

**Issue by device25** [urbica/eslint-config-urbica#4]
In our [package.json](https://github.com/urbica/eslint-config-urbica/blob/master/package.json#L29) we use `babel-eslint@^10.0.1`. Current version is [10.0.2](https://github.com/babel/babel-eslint/releases/tag/v10.0.2)  but CRA need 10.0.1 version

> The react-scripts package provided by Create React App requires a dependency:
>
>  "babel-eslint": "10.0.1"

@stepankuzmin maybe we can fix out babel-eslint on 10.0.1 too? `"babel-eslint": "10.0.1"`

**Comment by stepankuzmin** [comment]
Could you please provide steps to reproduce this issue?

```shell
npx create-react-app app
cd app
yarn add -D eslint-config-urbica
yarn start
```

This works as expected.

**Comment by device25** [comment]
You can try installing CRA ^2.0.0 & eslint-config-urbica ^2.0.0 via npm, and then try to upgrade both to ^3.0.0. I will describe the steps tonight.

**Comment by device25** [comment]
@stepankuzmin you can reproduce it by this steps

```
mkdir test
cd test
touch package.json
``` 
`package.json`
```
{
  "devDependencies": {
    "eslint-config-urbica": "3.0.0",
    "react-scripts": "3.0.1"
  }
}
```
then
```
npm i
npm ls babel-eslint
```

Expect `babel-eslint@10.0.1`, but has
```
├─┬ eslint-config-urbica@3.0.0
│ └── babel-eslint@10.0.2 
└─┬ react-scripts@3.0.1
  └── babel-eslint@10.0.1 
```

My env
```
node --version
v12.6.0
npm --version
6.9.0
```

**Comment by stepankuzmin** [comment]
Well, this is actually a CRA issue https://github.com/facebook/create-react-app/issues/6129
